### ISSUE TITLE
Tests 28exception.t and 32boolean.t failing when installing on Ubuntu 14 LTS

### ISSUE THREAD

**Issue by rmikebaker** [niner/inline-python-pm#10]
Apologies in advance if this isn't appropriate here, but I'm having issues installing 0.49 on Ubuntu 14 LTS.  In particular, tests 28exception.t and 32boolean.t keep failing.  For example:

t/28exception.t ........ Error -- py_eval raised an exception at /root/.cpan/build/Inline-Python-0.49-7nO47o/blib/lib/Inline/Python.pm line 177.
BEGIN failed--compilation aborted at t/28exception.t line 7.

I tried the normal CPAN install, as well as a manual install, and get the same results with both.  I went ahead and forced the install using CPAN, and my quick tests indicate it seems to be working, but it doesn't give me the warm-n-fuzzy feeling with those two tests failing.

**Comment by niner** [comment]
No worry, this is the right place. What python version are you using Inline::Python with?

**Comment by rmikebaker** [comment]
Sorry, I should have mentioned that :(

I'm using python 3.4.0

**Comment by niner** [comment]
Ok, sounds like the Python code in those two test files is just not Python 3.4 compatible. Inline::Python was developed for Python 2 and got Python 3 support through patches by Laurent Mazuel. I still regularily only test on Python 2, since that's what we're using.

If you know Python 3, it would be great if you could have a look at those two tests and see if the Python code can be written in a way that's Python 2+3 compatible. t/20unicode.t might be of help there.

**Comment by rmikebaker** [comment]
Thanks for the quick response.  I'll take a look and see what I can do...

**Comment by lmazuel** [comment]
Hi!
I made a pull request for that. Only the unit tests had to be fixed.
Have a nice day!

**Comment by niner** [comment]
Excellent! Many thanks for fixing this :)

And thanks for to rmikebaker for reporting!
